# Eureka configuration
spring:
  application:
    name: eureka-discovery-service
  server:
    port: 8761
  cloud:
    config:
      uri: http://localhost:8888
  eureka:
    client:
      fetch-registry: false
      register-with-eureka: false
